name: Dynamic Service Matrix

on:
  push:

jobs:
  detect-services:
    runs-on: ubuntu-latest

    outputs:
      services: ${{ steps.set.outputs.services }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Detect Services
        id: set
        run: |
          echo 'services=["user-service","payment-service"]' >> $GITHUB_OUTPUT

  test-services:
    needs: detect-services
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: ${{ fromJson(needs.detect-services.outputs.services) }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Test Service
        run: |
          echo "Testing ${{ matrix.service }}"
          cd services/${{ matrix.service }}
          mvn test
